name: Ruff

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803  # v6.1.0
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7.6.0
        with:
          enable-cache: true
          prune-cache: false
          cache-dependency-glob: pyproject.toml
          cache-suffix: ruff
      - name: "Linting"
        run: uvx ruff@0.15.8 check  # Keep in sync with pyproject.toml
      - name: "Formatting"
        run: uvx ruff@0.15.8 format --check
